### ISSUE TITLE
How we handle piping data is really bad

### ISSUE THREAD

**Issue by Zyber17** [nulltitleexception/FellJS#2]
How we send/handle incoming data is really bad (see [Game.js lines 39–49](https://github.com/nulltitleexception/FellJS/blob/gh-pages/assets/js/game.js#L39-49)). We should probabl;y be passing a JSON object to it containing multiple sets of data if needed. Something like, hypothetically:

``` json
{
    "dat": [23,42],
    "dat": [-12,3],
    "dat": [29,32],
    "pos": [43,97,22,0],
    "err": {
        "code": 001,
        "isFatal": false
    }
}
```

It's allow us a lot more flexibility (including passing multiple messages at once), remove the need for weird `string.indexOf`/`string.split` BS, and just be way better practice in general.

**Comment by Zyber17** [comment]
BTW, these issues are just as much a note-to-self as they are a thing I'm mentioning to you.

**Comment by Zyber17** [comment]
Pssst. If we're done moving to JSON (I'm not sure if we are), you should mark this as closed.

**Comment by phi-fell** [comment]
all fixed for server messages.
